# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/j9110/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter guacamole guacamoleb guacamoleg hotdog hotdogb,$(TARGET_DEVICE)),)

endif
